#!/usr/bin/env perl

use strict;
use warnings;


use Data::Dumper;
use File::Basename;
use File::Find;
use Text::Markdown 'markdown';

if ( ! -e "index.md" ) {
    die "You need to run from the root of the content, with a index.md file on it\n";
}

my @files_list = ();
my @links_list = ();

find( \&wanted, "." );

for my $page ( @files_list ) {
    next if  ( basename( $page ) eq "index.md" );
    my $pagename = $page;
    $pagename =~ s/\.md$//;
    push @links_list, [ $pagename, "$pagename.html" ];
    print "Generating page for $page\n";
    # try tiny
    local $/;
    open my $fh, "<", $page;
    my $slurped = <$fh>;
    close $fh;
    my $html = markdown( $slurped );
    open my $o_fh, ">", $pagename . ".html";
    print $o_fh $html;
    close $o_fh;
}

# index
my $index_link_list = "### List of notes\n";
for my $link ( @links_list ) {
    $index_link_list .= "* [$link->[0]]( $link->[1] )\n";
}

open my $fh, "<", "index.md";
local $/;
my $index = <$fh>;
$index .= $index_link_list;
my $html = markdown( $index );
open my $o_fh, ">", "index.html";
print $o_fh $html;
close $o_fh;

sub wanted {
    if ( $_ =~ /\.md$/ ) {
        push @files_list, $File::Find::name;
    }
}
